backend:
  name: github
  repo: keonik/dev-portfolio
media_folder: content/img
public_folder: /img
publish_mode: editorial_workflow
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: lastUpdated, label: Last Updated, widget: datetime }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: tldr, label: TLDR, required: false }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }
      - { name: tags, label: Tags, widget: list }
  - name: project
    label: Projects
    folder: content/projects
    create: true
    fields:
      - { name: title, label: Title }
      - { name: link, label: Link, required: false }
      - { name: github, label: Github, required: false }
      - { name: description, label: Description, widget: markdown }
      - { name: tags, label: Tags, widget: list }
      - { name: image, label: Image, widget: image }
      - { name: date, label: Date, widget: date }
      - { name: lastUpdated, label: Last Updated, widget: datetime }
